account/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='account'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.loggedin, name='login'),
    path('logout/', views.loggedout, name='logout'),
    path('user/<int:id>', views.account),
]

event/urls.py
from django.urls import path
from . import views


app_name = 'events'

urlpatterns = [
    path('<int:id>', views.events, name='gallery'),
    path('<int:id>/comment', views.eventComment, name='comment')
]

ppwkd2/urls.py
from django.urls import path, include
from django.contrib import admin
from landingpage.views import landing
from django.conf.urls.static import  static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing, name="home"),
    path('get/', include('landingpage.urls'), name="gethome"),
    path('contact/', include('contact.urls'),name="contact"),
    path('event-regis/', include('registerevent.urls'), name ="registerevent"),
    path('events/', include('event.urls'), name="event"),
    path('join/', include('joinevent.urls'), name="join"),
    path('account/', include('account.urls'), name="account"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models

# Create your models here.

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.core.serializers import serialize

def signup(request):
    if request.user.is_authenticated:
        return redirect('home')
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            user = User.objects.get(username=request.POST.get('username'))
            login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form':form})

def loggedin(request):
    if request.user.is_authenticated:
        return redirect('home')
    if request.method ==  'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('home')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form':form})
  
def loggedout(request):
    # if request.method == 'POST':
    logout(request)
    return redirect('home')

def account(request, id):
    user = User.objects.get(id=id)
    data = serialize('json', [user])
    return JsonResponse(data, safe=False)

account/templates/login.html
{% extends 'baseNavBar.html' %}

{% load static %}

{% block title %}
    LOGIN
{% endblock title %}

{% block page%}


<div>
    <div class="bodyLogin"></div>
            <div class="grad"></div>
            <div class="header">
                <div>EVENT<span>.in</span></div>
            </div>
            <br>
            <div class="login">
                <form action="{% url 'account:login' %}" method="POST">
                    {% csrf_token %}
                    {{ form }}
                    <!-- <input type="text" placeholder="username" name="user"><br>
                    <input type="password" placeholder="password" name="password"><br> -->
                    <input type="submit" value="login">
                    <p class="login__signup">Don't have an account? &nbsp;<a href="{% url 'account:signup' %}">Sign up</a></p>
                </form>
            </div>
</div>
        
{% endblock page%}

{% block css %} 
<link rel="stylesheet" href="{% static 'css/signup.css' %}">
<link rel="stylesheet" href="{% static 'css/login.css' %}">
    
    {% endblock css%}

account/templates/signup.html
{% extends 'baseNavBar.html' %}

{% load static %}


{% block title %}
    SIGN UP
{% endblock title %}

{% block page%}
<div>
        <div class="bodySignup"></div>
                <div class="grad"></div>
                <div class="header">
                    <div>EVENT<span>.in</span></div>
                </div>
                <br>
                <div class="login">
                    <form action="{% url 'account:signup' %}" method="POST">
                        {% csrf_token %}
                        {{ form }}
                        
                        <!-- <input type="text" placeholder="username" name="user"><br>
                        <input type="password" placeholder="password" name="password"><br> -->
                        <input type="submit" value="Sign Up">
                    </form>
                </div>
    </div>
        
{% endblock page%}

<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Signup</title>
</head>
<body>
    Signup
    <form action="{% url 'account:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" name="" id="" value="Signup">
    </form>
</body>
</html> -->

{% block css %} 
<link rel="stylesheet" href="{% static 'css/signup.css' %}">
<link rel="stylesheet" href="{% static 'css/login.css' %}">
    
    {% endblock css%}