account/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='account'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.loggedin, name='login'),
    path('logout/', views.loggedout, name='logout'),
    path('user/<int:id>', views.account),
]

event/urls.py
from django.urls import path
from . import views


app_name = 'events'

urlpatterns = [
    path('<int:id>', views.events, name='gallery'),
    path('<int:id>/comment', views.eventComment, name='comment')
]

ppwkd2/urls.py
from django.urls import path, include
from django.contrib import admin
from landingpage.views import landing
from django.conf.urls.static import  static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing, name="home"),
    path('get/', include('landingpage.urls'), name="gethome"),
    path('contact/', include('contact.urls'),name="contact"),
    path('event-regis/', include('registerevent.urls'), name ="registerevent"),
    path('events/', include('event.urls'), name="event"),
    path('join/', include('joinevent.urls'), name="join"),
    path('account/', include('account.urls'), name="account"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/baseNavBar.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/gallery.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/pendaftaranevent.css' %}">
    {% block css %} 
    
    {% endblock css%}
    <link href="https://fonts.googleapis.com/css?family=Sansita&display=swap" rel="stylesheet">
    

    <title>
    {% block title %}
    
    {% endblock title%}
    </title>
    
  </head>

  <body>
    
    <div class="container-fluid">
      <div class="row right-content-center row1">
        <div class="col-md-12  bg-dark">
          <nav class="navbar navbar-expand-lg ">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav ml-auto textInfo navItem">
                <a class="nav-item nav-link navBar" href="{% url 'home' %}">Home <span class="sr-only"></span></a>
                <a class="nav-item nav-link navBar" href="{% url 'pendaftaran' %}">Register Event</a>
                <a class="nav-item nav-link navBar" href="{% url 'contact' %}">Contact</a>
                {% if user.is_authenticated %}
                <a class="nav-item nav-link navBar" href="{% url 'account:logout' %}">Logout {{user}}</a>
                {% else %}
                <a class="nav-item nav-link navBar" href="{% url 'account:login' %}">Login</a>
                {% endif %}
              </div>
            </div>
          </nav>
        </div>
      </div>
    </div> 

    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>

    {% block page %} 

    {% endblock page %}

    <hr class= 'hr'>
    <footer id="sticky-footer" class="py-4 bg-dark text-white-50 , footer">	
      <div class="container text-center">
          <small>Copyright &copy; Event.in</small>
      </div>
	  </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    
    </body>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'js/joinevent.js' %}"></script>
    {% block script %}
    {% endblock script %}
    {% block js %}
    {% endblock js %}

    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <!-- <script src="{% static 'scripts/eventgallery.js' %}"></script> -->
    </body>
</html>