event/urls.py
from django.urls import path
from . import views


app_name = 'events'

urlpatterns = [
    path('<int:id>', views.events, name='gallery'),
    path('<int:id>/comment', views.eventComment, name='comment')
]

ppwkd2/urls.py
from django.urls import path, include
from django.contrib import admin
from landingpage.views import landing
from django.conf.urls.static import  static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing, name="home"),
    path('get/', include('landingpage.urls'), name="gethome"),
    path('contact/', include('contact.urls'),name="contact"),
    path('event-regis/', include('registerevent.urls'), name ="registerevent"),
    path('events/', include('event.urls'), name="event"),
    path('join/', include('joinevent.urls'), name="join"),
    path('account/', include('account.urls'), name="account"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registerevent/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.event_form, name='pendaftaran'),
	path('json-event', views.get_data_event_regis, name='json-data'),
]

event/models.py
from django.db import models
from django.contrib.auth.models import User
from registerevent.models import EventRegis

# Create your models here.
class EventComment(models.Model):
    comment = models.TextField(blank = True, null = True, max_length = 500)
    author = models.ForeignKey(User, default=None, on_delete=models.PROTECT)
    eventRegis = models.ForeignKey(EventRegis, default=None, on_delete=models.PROTECT)
    

registerevent/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class EventRegis (models.Model):
	location = models.CharField(max_length=50)
	corporate_name = models.CharField(max_length=50)
	address = models.CharField(max_length=50)
	email = models.EmailField(max_length=50)
	event = models.CharField(max_length=50)
	tanggal = models.DateField()
	waktu = models.TimeField()	
	image = models.ImageField(upload_to="Images", default="Images/default.jpeg")
	desc = models.TextField(max_length = 1000)
	

event/forms.py
from django import forms
from django.forms import TextInput
from . import models


class CreateComment(forms.ModelForm):
    class Meta:
        model = models.EventComment
        fields = ['comment']

    # def __init__(self, *args, **kwargs):
    #     super(CreateComment, self).__init__(*args, **kwargs)
    #     self.fields['comment'].widget = TextInput(attrs={
    #         'id': 'fieldName',
    #         'class': 'site-form',
    #     })

registerevent/forms.py
from django import forms
from .models import EventRegis
from django.forms import ModelForm

class EventForm (ModelForm):
    class Meta:
        model = EventRegis
        fields = ['location', 'corporate_name', 'address','tanggal','waktu', 'email', 'event', 'image', 'desc']
        labels = {
            'location' : 'Location', 'corporate_name' : 'Corporate Name', 'address' : 'Address', 'tanggal': 'Tanggal', 'waktu': 'Waktu', 'email' : 'Email', 'event' : 'Event', 'image' : 'Image', 'desc' : ''}
        widgets = {
            'location' : forms.TextInput(
                attrs = {'class': 'form-control',
                        'type' : 'text',
                        'placeholder' : 'Location'}),
            'corporate_name' : forms.TextInput(attrs={'class': 'form-control',
                                        'type' : 'text',
                                        'placeholder' : 'Corporate Name'}),
            'address' : forms.TextInput(attrs={'class': 'form-control',
                                        'type' : 'text',
                                        'placeholder' : 'Address'}),
            'tanggal' : forms.DateInput(attrs={"class" : "form-control",
                                        'placeholder' : 'Tanggal (mm/dd/yyyy)'}),
            'waktu' : forms.TimeInput(attrs={
                                        "class" : "form-control",
                                        "placeholder":"Waktu (00:00)",
                                        }),
            'event' : forms.TextInput(attrs={'class': 'form-control',
                                        'type' : 'text',
                                        'placeholder' : 'Event'}),
            'email' : forms.TextInput(attrs={'class': 'form-control',
                                        'type' : 'text',
                                        'placeholder' : 'Email'}),
            'image' : forms.FileInput(),
            'desc' : forms.Textarea(attrs={'class': 'form-control',
                                        'placeholder' : 'Event Description'})
        }

event/views.py
from django.shortcuts import render, redirect
from .forms import CreateComment
from registerevent.models import EventRegis
from django.http import JsonResponse
from .models import EventComment
from django.core.serializers import serialize


def events(request,id):
    events = EventRegis.objects.get(id=id)
    if request.method == 'POST':
        if request.user.is_authenticated:
            # print('testtt')
            form = CreateComment(request.POST, request.FILES)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.author = request.user
                instance.eventRegis = events
                instance.save()
                return redirect('events:gallery', id)
        return redirect('account:login')
    else:
        form = CreateComment()
    return render(request, 'gallery.html', {'form': form, 'event': events})

def eventComment(request,id):
    events = EventRegis.objects.get(id=id)
    comment = EventComment.objects.filter(eventRegis=events)
    data = serialize('json', comment)
    # serializers.serialize('json', posts)
    return JsonResponse(data, safe=False)



    

registerevent/views.py
from django.shortcuts import render
from .forms import EventForm
from .models import EventRegis
from django.shortcuts import redirect
from django.core import serializers
from django.http import HttpResponse

def event_form(request):
	pendaftaran_form = EventForm()
	if request.method == "POST" :
		pendaftaran_form = EventForm(request.POST, request.FILES)
		if pendaftaran_form.is_valid():
			print (request.POST)
			pendaftaran_form.save()
			
	context =  {
		'form' : pendaftaran_form
	}
	return render(request, 'event_form.html', context)

def get_data_event_regis(request):
	data = EventRegis.objects.all()
	list_data = serializers.serialize('json', data)
	return HttpResponse(list_data, content_type='text/json-comment-filtered')
# Create your views here.

registerevent/templates/event_form.html
{% extends 'baseNavBar.html' %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'css/pendaftaranevent.css' %}"> {% endblock css %} {% block title %} Event Registration {% endblock title %} {% block page %}

<body id="body_event_regis">
    <br/>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="container">
                    <center>
                        <h1 id="regis" style="font-family: 'Sansita', sans-serif;">Registration</h1>
                    </center>
                    <br>
                    <form id="form_create_event" method="POST" novalidate enctype="multipart/form-data">{% csrf_token %}
                        <div id="corporate_name" class="form-group">
                            {{form.corporate_name}}
                        </div>
                        <div id="address" class="form-group">
                            {{form.address}}
                        </div>
                        <div id="email" class="form-group">
                            {{form.email}}
                            <small class="form-text text-muted">We'll never share your email with anyone else.</small>
                        </div>
                        <div id="event" class="form-group">
                            {{form.event}}
                        </div>
                        <div class="form-group">
                            {{form.location}}
                        </div>
                        <div class="form-group">
                            {{form.tanggal}}
                        </div>
                        <div class="form-group">
                            {{form.waktu}}
                        </div>
                        <div class="form-group">
                            {{form.desc}}
                            <small class="form-text text-muted">Maximum word that you can fill only 60 words</small>
                        </div>
                        <div class="form-group">
                            {{form.image}}
                        </div>
                        <br>
                </div>
            </div>
        </div>
        <button id="button_create_event" style="float: right;" type="submit" class="btn btn-warning">Send</button>
        </form>
    </div>
    <br/>
    <br/>

    <script>
        $(document).on('submit', '#form_create_event', function(e) {
            e.preventDefault();
            $.ajax({
                type: "POST",
                url: '/event-regis/',
                data: {
                    corporate_name: $('#id_corporate_name').val(),
                    address: $('#id_address').val(),
                    email: $('#id_email').val(),
                    event: $('#id_event').val(),
                    location: $('#id_location').val(),
                    tanggal: $('#id_tanggal').val(),
                    waktu: $('#id_waktu').val(),
                    desc: $('#id_desc').val(),
                    image: $('#id_image').val(),
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                },
                success: function(res) {
                    $(location).attr('href', '{% url "pendaftaran" %}');

                }
            });
        })
    </script>

    <script>
        $("#regis").mouseover(function() {
            $(this).css("color", 'rgb(255, 196, 0)');
        });

        $("#regis").mouseleave(function() {
            $(this).css("color", 'black');
        });

        $("#button_create_event").click(function() {
            alert("Terimakasih");
        });
    </script>
    {% endblock page %}